version: 2
jobs:
  build:
    
    working_directory: ~/server/conferencebuddy-parent

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout
      
      - run: mvn install
